### ISSUE TITLE
using tempi beat to search only for certain range of frequency. 

### ISSUE THREAD

**Issue by steve21124** [jscalo/TempiBeatDetection#3]
is it possible to use tempi beat to search only for certain range of frequency and record it?

**Comment by jscalo** [comment]
TempiBeatDetection is about finding beats and tempos, not frequencies. That said, what you're describing shouldn't be hard if you use a similar algorithm: run the FFT over chunks of audio until the freq range you're interested in exceeds a certain magnitude, then save of the audio samples until the magnitude dips under the threshold. You can use [TempiFFT](https://github.com/jscalo/tempi-fft/tree/master/TempiFFT) to help with the FFT work.

**Comment by steve21124** [comment]
Thanks. good tips
