### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by CocosWong** [jscalo/TempiBeatDetection#4]
Thanks for your nice work!

I'm just trying to use `TempiBeatDetection` to detect a song's BPM.
Is it correct way to install if I just copy the files↓ to my project?

> TempiAudioInput.swift
> TempiBeatDetector.swift
> TempiBeatDetectorValidation.swift
> TempiDSP.swift
> TempiFFT.swift
> TempiPeakDetector.swift
> TempiUtilities.swift

And  is `TempiBeatDetection` available through CocoaPods?

**Comment by jscalo** [comment]
Yep, you can just add those files to your project (assuming Xcode 8.x) except I don't think TempiPeakDetector.swift is currently in use so you can skip that. Take a look at the sample project for an example. Sorry, I don't have it set up with CocoaPods.

**Comment by CocosWong** [comment]
Thank you ! I got it!
